In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder

In [16]:
df=pd.read_csv("teams.csv")
df

,team,country,year,events,athletes,age,height,weight,medals,prev_medals,prev_3_medals
0,AFG,Afghanistan,1964,8,8,22.0,161.0,64.2,0,0.0,0.0
1,AFG,Afghanistan,1968,5,5,23.2,170.2,70.0,0,0.0,0.0
2,AFG,Afghanistan,1972,8,8,29.0,168.3,63.8,0,0.0,0.0
3,AFG,Afghanistan,1980,11,11,23.6,168.4,63.2,0,0.0,0.0
4,AFG,Afghanistan,2004,5,5,18.6,170.8,64.8,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2139,ZIM,Zimbabwe,2000,19,26,25.0,179.0,71.1,0,0.0,0.0
2140,ZIM,Zimbabwe,2004,11,14,25.1,177.8,70.5,3,0.0,0.0
2141,ZIM,Zimbabwe,2008,15,16,26.1,171.9,63.7,4,3.0,1.0
2142,ZIM,Zimbabwe,2012,8,9,27.3,174.4,65.2,0,4.0,2.3
2143,ZIM,Zimbabwe,2016,13,31,27.5,167.8,62.2,0,0.0,2.3

In [17]:
plt.scatter(df["Age"],df["Occupation"])

KeyError: 'Age'

In [ ]:
da = df.drop(columns=["Therapy Sessions (per month)","Recent Major Life Event"])
da

In [5]:
x=df.iloc[:,0:-4]
x
y=df.iloc[:,-1]
y

0        10
1         8
2         5
3         8
4         1
         ..
11995     6
11996     6
11997    10
11998     5
11999     2
Name: Severity of Anxiety Attack (1-10), Length: 12000, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Gender_encoded"] = le.fit_transform(df["Gender"])
print(df)

          ID  Age  Gender Occupation  Sleep Hours  \
0          1   56  Female      Other          9.6
1          2   46    Male    Teacher          6.4
2          3   32  Female     Doctor          6.9
3          4   60    Male     Doctor          9.2
4          5   25    Male    Student          9.2
...      ...  ...     ...        ...          ...
11995  11996   28    Male   Engineer          4.4
11996  11997   49  Female     Doctor          9.9
11997  11998   23  Female    Student          9.8
11998  11999   52    Male    Teacher          5.9
11999  12000   50    Male    Teacher          6.6

       Physical Activity (hrs/week)  Caffeine Intake (mg/day)  \
0                               8.3                       175
1                               7.3                        97
2                               1.0                       467
3                               3.7                       471
4                               2.5                       364
...                             ...                       ...
11995                           4.1                       360
11996                           2.2                       433
11997                           8.1                       140
11998                           6.6                       114
11999                           7.8                       114

       Alcohol Consumption (drinks/week) Smoking Family History of Anxiety  \
0                                      6      No                        No
1                                      6      No                        No
2                                     14      No                        No
3                                     16      No                       Yes
4                                      2      No                       Yes
...                                  ...     ...                       ...
11995                                  1     Yes                       Yes
11996                                  4      No                       Yes
11997                                 19     Yes                        No
11998                                 12      No                        No
11999                                  0      No                        No

       ...  Heart Rate (bpm during attack)  Breathing Rate (breaths/min)  \
0      ...                             145                            33
1      ...                             143                            18
2      ...                              60                            34
3      ...                              94                            19
4      ...                             152                            15
...    ...                             ...                           ...
11995  ...                             139                            20
11996  ...                             150                            33
11997  ...                              81                            33
11998  ...                              90                            14
11999  ...                             107                            19

       Sweating Level (1-5)  Dizziness Medication  \
0                         3         No         No
1                         5        Yes         No
2                         1         No         No
3                         1         No        Yes
4                         4         No        Yes
...                     ...        ...        ...
11995                     2        Yes         No
11996                     2         No         No
11997                     2         No         No
11998                     5         No         No
11999                     2         No        Yes

      Therapy Sessions (per month)  Recent Major Life Event  \
0                                4                      Yes
1                                0                       No
2                                7                      Yes
3                                4                      Yes
4                                0                       No
...                            ...                      ...
11995                            7                       No
11996                            3                       No
11997                            8                       No
11998                            3                       No
11999                            3                       No

      Diet Quality (1-10)  Severity of Anxiety Attack (1-10)  Gender_encoded
0                       9                                 10               0
1                       9                                  8               1
2                      10                                  5               0
3                       5                                  8               1
4                       1                                  1               1
...                   ...                                ...             ...
11995                   9                                  6               1
11996                   5                                  6               0
11997                   1                                 10               0
11998                   9                                  5               1
11999                   8                                  2               1

[12000 rows x 21 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

# Create the LabelEncoder object
le = LabelEncoder()

# Fit and transform the "Occupation" column and assign the result to a new column
df["Occupation_encoded"] = le.fit_transform(df["Occupation"])

# Show the transformed DataFrame
print(df)

          ID  Age  Gender Occupation  Sleep Hours  \
0          1   56  Female      Other          9.6
1          2   46    Male    Teacher          6.4
2          3   32  Female     Doctor          6.9
3          4   60    Male     Doctor          9.2
4          5   25    Male    Student          9.2
...      ...  ...     ...        ...          ...
11995  11996   28    Male   Engineer          4.4
11996  11997   49  Female     Doctor          9.9
11997  11998   23  Female    Student          9.8
11998  11999   52    Male    Teacher          5.9
11999  12000   50    Male    Teacher          6.6

       Physical Activity (hrs/week)  Caffeine Intake (mg/day)  \
0                               8.3                       175
1                               7.3                        97
2                               1.0                       467
3                               3.7                       471
4                               2.5                       364
...                             ...                       ...
11995                           4.1                       360
11996                           2.2                       433
11997                           8.1                       140
11998                           6.6                       114
11999                           7.8                       114

       Alcohol Consumption (drinks/week) Smoking Family History of Anxiety  \
0                                      6      No                        No
1                                      6      No                        No
2                                     14      No                        No
3                                     16      No                       Yes
4                                      2      No                       Yes
...                                  ...     ...                       ...
11995                                  1     Yes                       Yes
11996                                  4      No                       Yes
11997                                 19     Yes                        No
11998                                 12      No                        No
11999                                  0      No                        No

       ...  Breathing Rate (breaths/min)  Sweating Level (1-5)  Dizziness  \
0      ...                            33                     3         No
1      ...                            18                     5        Yes
2      ...                            34                     1         No
3      ...                            19                     1         No
4      ...                            15                     4         No
...    ...                           ...                   ...        ...
11995  ...                            20                     2        Yes
11996  ...                            33                     2         No
11997  ...                            33                     2         No
11998  ...                            14                     5         No
11999  ...                            19                     2         No

       Medication Therapy Sessions (per month) Recent Major Life Event  \
0              No                            4                     Yes
1              No                            0                      No
2              No                            7                     Yes
3             Yes                            4                     Yes
4             Yes                            0                      No
...           ...                          ...                     ...
11995          No                            7                      No
11996          No                            3                      No
11997          No                            8                      No
11998          No                            3                      No
11999         Yes                            3                      No

       Diet Quality (1-10) Severity of Anxiety Attack (1-10)  Gender_encoded  \
0                        9                                10               0
1                        9                                 8               1
2                       10                                 5               0
3                        5                                 8               1
4                        1                                 1               1
...                    ...                               ...             ...
11995                    9                                 6               1
11996                    5                                 6               0
11997                    1                                10               0
11998                    9                                 5               1
11999                    8                                 2               1

       Occupation_encoded
0                       2
1                       4
2                       0
3                       0
4                       3
...                   ...
11995                   1
11996                   0
11997                   3
11998                   4
11999                   4

[12000 rows x 22 columns]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [9]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9600 entries, 3169 to 5994
Data columns (total 16 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 9600 non-null   int64
 1   Age                                9600 non-null   int64
 2   Gender                             9600 non-null   object
 3   Occupation                         9600 non-null   object
 4   Sleep Hours                        9600 non-null   float64
 5   Physical Activity (hrs/week)       9600 non-null   float64
 6   Caffeine Intake (mg/day)           9600 non-null   int64
 7   Alcohol Consumption (drinks/week)  9600 non-null   int64
 8   Smoking                            9600 non-null   object
 9   Family History of Anxiety          9600 non-null   object
 10  Stress Level (1-10)                9600 non-null   int64
 11  Heart Rate (bpm during attack)     9600 non-null   int64
 12  Breathing Rate (breaths/min)       9600 non-null   int64
 13  Sweating Level (1-5)               9600 non-null   int64
 14  Dizziness                          9600 non-null   object
 15  Medication                         9600 non-null   object
dtypes: float64(2), int64(8), object(6)
memory usage: 1.2+ MB

In [10]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2400 entries, 7612 to 4437
Data columns (total 16 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 2400 non-null   int64
 1   Age                                2400 non-null   int64
 2   Gender                             2400 non-null   object
 3   Occupation                         2400 non-null   object
 4   Sleep Hours                        2400 non-null   float64
 5   Physical Activity (hrs/week)       2400 non-null   float64
 6   Caffeine Intake (mg/day)           2400 non-null   int64
 7   Alcohol Consumption (drinks/week)  2400 non-null   int64
 8   Smoking                            2400 non-null   object
 9   Family History of Anxiety          2400 non-null   object
 10  Stress Level (1-10)                2400 non-null   int64
 11  Heart Rate (bpm during attack)     2400 non-null   int64
 12  Breathing Rate (breaths/min)       2400 non-null   int64
 13  Sweating Level (1-5)               2400 non-null   int64
 14  Dizziness                          2400 non-null   object
 15  Medication                         2400 non-null   object
dtypes: float64(2), int64(8), object(6)
memory usage: 318.8+ KB

In [11]:
y_test.info()

<class 'pandas.core.series.Series'>
Index: 2400 entries, 7612 to 4437
Series name: Severity of Anxiety Attack (1-10)
Non-Null Count  Dtype
--------------  -----
2400 non-null   int64
dtypes: int64(1)
memory usage: 37.5 KB

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lr=LinearRegression()

In [14]:
lr.fit(x_train,y_train)

ValueError: could not convert string to float: 'Male'